clear_on_pause = true
interval = 2000

[template]
detail = "{{{title}}}"
state = "{{{artist_display}}}"
large_text = "{{#if album}}{{{album}}}{{#if year}} ({{{year}}}){{/if}}{{#if album_artist_display}} by {{{album_artist_display}}}{{/if}}{{/if}}"
small_text = "{{#if player}}Playing on {{{player}}}{{else}}MPRIS{{/if}}"

[time]
show = true
as_elapsed = false

[activity_type]
use_content_type = true
default = "listening"

[cover]
file_names = ["cover", "folder", "front", "album", "art"]
local_search_depth = 2

[cover.provider]
provider = ["musicbrainz"]

[cover.provider.musicbrainz]
min_score = 95

[player]
default = { ignore = true, app_id = "1121632048155742288", icon = "https://raw.githubusercontent.com/lazykern/mprisence/main/assets/icon.png", show_icon = false, allow_streaming = false }

[player.strawberry]
ignore = false
app_id = "1126197744512536647"
icon = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Strawberry-icon-1000px.png/800px-Strawberry-icon-1000px.png"
allow_streaming = true

[player.youtube_music]
ignore = false
app_id = "1125082278339559505"
icon = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Youtube_Music_icon.svg/768px-Youtube_Music_icon.svg.png"
allow_streaming = true